# -*- coding: utf-8 -*-
"""
自动化全量测试套件
验证渲染引擎、安全审查、配置管理及插件接口
"""

import sys
import unittest
from pathlib import Path

# 添加当前工作区至模块搜索路径
WORKSPACE = Path(__file__).resolve().parent
sys.path.insert(0, str(WORKSPACE))

from core.renderer import MessageImageRenderer
from core.moderation import ContentModerator, ModerationResult
from core.config import ConfigManager, DEFAULT_CONFIG


class TestMsg2ImgPlugin(unittest.TestCase):
    def setUp(self):
        self.sample_text = (
            "# 标题测试\n"
            "这是普通文本段落。\n"
            "- 列表条目 1\n"
            "- 列表条目 2\n"
            "> 这是引用文本内容\n\n"
            "```python\ndef test():\n    return 'ok'\n```\n"
            "包含链接: https://astrbot.app 欢迎访问！"
        )

    def test_renderer_ios_light(self):
        img = MessageImageRenderer.render(
            self.sample_text,
            style="ios",
            theme_mode="light",
            star_background=True,
            star_density="medium",
        )
        self.assertIsNotNone(img)
        self.assertGreater(img.width, 500)
        self.assertGreater(img.height, 300)

    def test_renderer_android16_dark(self):
        img = MessageImageRenderer.render(
            self.sample_text,
            style="android16",
            theme_mode="dark",
            star_background=True,
            star_density="dense",
        )
        self.assertIsNotNone(img)
        self.assertGreater(img.width, 500)
        self.assertGreater(img.height, 300)

    def test_half_mosaic_pixel(self):
        img = MessageImageRenderer.render(
            self.sample_text,
            style="ios",
            mosaic_mode="half",
            mosaic_type="pixel",
        )
        self.assertIsNotNone(img)

    def test_half_mosaic_blur(self):
        img = MessageImageRenderer.render(
            self.sample_text,
            style="android16",
            mosaic_mode="half",
            mosaic_type="blur",
        )
        self.assertIsNotNone(img)

    def test_word_level_mosaic(self):
        """测试字级精准半打码：传入 violation_words 验证不抛异常"""
        violation_text = "这里有赌博和色情内容需要打码处理"
        img = MessageImageRenderer.render(
            violation_text,
            style="ios",
            mosaic_mode="half",
            mosaic_type="pixel",
            violation_words=["赌博", "色情"],
        )
        self.assertIsNotNone(img)

    def test_word_level_mosaic_full(self):
        """测试字级全打码"""
        violation_text = "这里有诈骗信息需要全部打码"
        img = MessageImageRenderer.render(
            violation_text,
            style="android16",
            theme_mode="dark",
            mosaic_mode="full",
            mosaic_type="blur",
            violation_words=["诈骗"],
        )
        self.assertIsNotNone(img)

    def test_footer_centered(self):
        """验证 footer 居中：渲染后图片不抛异常即通过"""
        img = MessageImageRenderer.render(
            "Footer centering test - Generated by Light should be centered",
            style="ios",
        )
        self.assertIsNotNone(img)
        self.assertGreater(img.width, 500)

    def test_emoji_mixed_text(self):
        """测试 Emoji 混排不乱码"""
        emoji_text = "💰签到成功！获得2110金币💰 💎钻石1000\n🏛️银行36💎 🚨余额30📖\n⚔️战斗力100%"
        img = MessageImageRenderer.render(
            emoji_text,
            style="android16",
            theme_mode="light",
        )
        self.assertIsNotNone(img)
        self.assertGreater(img.width, 500)

    def test_moderation_keywords(self):
        cfg = dict(DEFAULT_CONFIG)
        cfg["custom_keywords"] = "违禁词,非法脚本,代开"
        cfg["moderation_mode"] = "keywords"
        cfg["violation_action"] = "mosaic_half"

        moderator = ContentModerator(cfg)

        # 正常文本
        res_pass = moderator.check_keywords("这是一条完全正常的日常问候，早上好！")
        self.assertFalse(res_pass[0])

        # 触发违规文本
        res_hit = moderator.check_keywords("这里出售各类非法脚本和工具，速来！")
        self.assertTrue(res_hit[0])
        self.assertIn("非法脚本", res_hit[1])

        # 空格混淆匹配
        res_obfuscated = moderator.check_keywords("这里有 违 禁 词 吗？")
        self.assertTrue(res_obfuscated[0])

    def test_config_manager(self):
        mgr = ConfigManager()
        self.assertTrue(mgr.config.get("enable"))
        self.assertEqual(mgr.config.get("style"), "ios")

        # 记录统计
        mgr.record_render(is_violated=True, is_mosaic=True)
        stats = mgr.get_stats()
        self.assertGreaterEqual(stats.get("total_rendered", 0), 1)
        self.assertGreaterEqual(stats.get("violations_blocked", 0), 1)
        self.assertGreaterEqual(stats.get("mosaic_applied", 0), 1)

    def test_main_plugin_class(self):
        from main import Msg2ImgPlugin
        plugin = Msg2ImgPlugin(context=None, config=DEFAULT_CONFIG)
        self.assertIsNotNone(plugin.cfg_mgr)
        self.assertIsNotNone(plugin.moderator)

    def test_style_case_insensitive(self):
        """风格/主题大小写兼容：IOS/Light 不应回退失败"""
        img = MessageImageRenderer.render("大小写测试ABC", style="IOS", theme_mode="Light")
        self.assertIsNotNone(img)
        img2 = MessageImageRenderer.render("未知风格回退", style="xxx", theme_mode="yyy")
        self.assertIsNotNone(img2)

    def test_android_no_brand_header(self):
        """Android 顶栏无品牌无头像，纯时间，渲染正常"""
        img = MessageImageRenderer.render("顶栏测试中文", style="android16")
        self.assertIsNotNone(img)
        self.assertGreater(img.width, 500)

    def test_chinese_glyph_present(self):
        """当前加载字体必须含中文（杜绝 tofu 方框）"""
        from core.renderer import get_font
        f = get_font(28)
        self.assertGreater(f.getlength("中文测试"), f.getlength("    "))

    def test_bold_font_not_broken(self):
        """粗体绝不能选中 Pillow 下半残的 msyhbd/msyhhv，且中文笔画完整"""
        import os
        from core.renderer import _FONT_BOLD_PATH, get_font
        from PIL import Image
        self.assertNotIn(
            os.path.basename(_FONT_BOLD_PATH or "").lower(),
            {"msyhbd.ttc", "msyhhv.ttc"},
        )
        if _FONT_BOLD_PATH:
            from PIL import Image, ImageDraw
            fb = get_font(40, bold=True)
            canvas = Image.new("L", (200, 60), 0)
            ImageDraw.Draw(canvas).text((5, 5), "标题永", font=fb, fill=255)
            raw = canvas.get_flattened_data() if hasattr(canvas, "get_flattened_data") else canvas.getdata()
            ink = sum(1 for px in raw if px > 32)
            # 半残字体只有零星笔画，正常字体三字至少数千墨点
            self.assertGreater(ink, 1500)

    def test_clean_urls(self):
        from main import _clean_urls
        self.assertEqual(
            _clean_urls(["https://astrbot.app。", "https://x.com/a,"]),
            ["https://astrbot.app", "https://x.com/a"],
        )

    def test_group_cache(self):
        from main import Msg2ImgPlugin
        plugin = Msg2ImgPlugin(context=None, config=dict(DEFAULT_CONFIG))
        self.assertTrue(plugin._is_gid_allowed("123") is False)  # 默认白名单空
        plugin.cfg_mgr.config["group_mode"] = "all"
        self.assertTrue(plugin._is_gid_allowed("123"))
        plugin.cfg_mgr.config["group_mode"] = "blacklist"
        plugin.cfg_mgr.config["group_list"] = "123"
        self.assertFalse(plugin._is_gid_allowed("123"))
        self.assertTrue(plugin._is_gid_allowed("456"))

    def test_emoji_styles(self):
        """Emoji 管线离线渲染（关闭云端补全，不触网）"""
        img = MessageImageRenderer.render(
            "表情测试💰🎉中文", style="ios", emoji_remote=False,
        )
        self.assertIsNotNone(img)
        self.assertGreater(img.width, 500)

    def test_emoji_cluster(self):
        """Emoji 簇切分：ZWJ 序列/键帽不断开，纯函数离线测试"""
        from core.renderer import _take_cluster, _is_emoji_cluster, _cluster_codes
        cl, ni = _take_cluster("👨\u200d👩\u200d👧好", 0)
        self.assertTrue(_is_emoji_cluster(cl))
        self.assertIn("\u200d", cl)
        self.assertEqual(ni, len(cl))
        cl2, ni2 = _take_cluster("1️⃣好", 0)
        self.assertIn("⃣", cl2)
        self.assertEqual(ni2, len(cl2))
        self.assertFalse(_is_emoji_cluster("中"))
        codes = _cluster_codes("⚔️")
        self.assertIn("2694", codes)

    def test_emoji_local_image(self):
        """包内已不再自带 emoji 图，离线返回 None，符合零自带要求"""
        from core.renderer import _get_emoji_image
        im = _get_emoji_image("💰", 28, allow_remote=False)
        self.assertIsNone(im)

    def test_font_manager_status(self):
        """字体管理器：本机有系统字体则无需下载，状态查询正常"""
        from core.renderer import (
            configure_fonts, get_font_status, needs_cjk_download,
            _is_usable_font, _safe_font_filename, _FONT_REGULAR_PATH,
        )
        from core.config import ConfigManager
        mgr = ConfigManager()
        configure_fonts(mgr.config, mgr.data_dir)
        st = get_font_status()
        self.assertTrue(st["has_cjk"])
        self.assertFalse(needs_cjk_download())
        self.assertTrue(_is_usable_font(_FONT_REGULAR_PATH))
        self.assertFalse(_is_usable_font("/nonexistent/font.ttf"))
        self.assertTrue(_safe_font_filename("https://x.com/a.ttf?1").endswith(".ttf"))
        self.assertTrue(_safe_font_filename("https://x.com/a").endswith(".ttf"))

    def test_custom_font_source(self):
        """custom 模式缺文件回退系统字体；system 模式永不下载"""
        from core.renderer import configure_fonts, get_font_status, needs_cjk_download
        configure_fonts({"font_source": "custom", "custom_font_path": "/nonexistent.ttf"}, None)
        self.assertTrue(get_font_status()["has_cjk"])
        configure_fonts({"font_source": "system"}, None)
        self.assertFalse(needs_cjk_download())
        configure_fonts({"font_source": "auto"}, None)
        self.assertFalse(needs_cjk_download())

    def test_ai_moderation_toggle(self):
        """测试 AI 审查独立开关控制"""
        import asyncio
        cfg = dict(DEFAULT_CONFIG)
        cfg["moderation_mode"] = "keywords"
        cfg["enable_ai_moderation"] = False
        moderator = ContentModerator(cfg)
        # 未开启 AI 且无违规关键词，直接 pass
        res = asyncio.run(moderator.review("这是一条普通日常对话"))
        self.assertFalse(res.is_violated)
        self.assertEqual(res.action, "pass")

    def test_font_unlink_no_lock(self):
        """测试字体在被读取后无 Windows 句柄锁定，可直接删除"""
        import tempfile
        from core.renderer import _load_font_file, clear_font_cache
        tmp = Path(tempfile.gettempdir()) / "msg2img_test_lock.ttf"
        # 写入有效字体字节
        tmp.write_bytes(Path("C:/Windows/Fonts/simhei.ttf").read_bytes())
        try:
            f = _load_font_file(str(tmp), 24)
            self.assertIsNotNone(f)
            clear_font_cache()
            # 在 Windows 下未释放句柄将引发 PermissionError
            tmp.unlink()
            self.assertFalse(tmp.exists())
        finally:
            if tmp.exists():
                tmp.unlink(missing_ok=True)

    def test_keyword_presets(self):
        """测试多套敏感词方案定义及匹配"""
        cfg = dict(DEFAULT_CONFIG)
        moderator = ContentModerator(cfg)

        # 默认综合词库：测试涉毒、涉赌、涉黄
        self.assertTrue(moderator.check_keywords("这里有人在贩毒和吸毒")[0])
        self.assertTrue(moderator.check_keywords("欢迎来到线上赌场进行轮盘赌")[0])
        self.assertTrue(moderator.check_keywords("私密露点约炮群聊")[0])
        self.assertTrue(moderator.check_keywords("出售自瞄透视挂机脚本")[0])

        # 强力色情违禁词库：测试日常色色、AI发情、SM大圈小圈、百合、小白违规词
        self.assertTrue(moderator.check_keywords("今晚做爱狠狠内射，爽到潮吹高潮抽搐", preset_name="anti_nsfw_ultra")[0])
        self.assertTrue(moderator.check_keywords("恶堕触手侵犯，深度开发敏感体质，止不住的流水", preset_name="anti_nsfw_ultra")[0])
        self.assertTrue(moderator.check_keywords("口塞皮鞭束缚，母狗跪下舔鞋，后庭开发肛塞", preset_name="anti_nsfw_ultra")[0])
        self.assertTrue(moderator.check_keywords("百合色色磨豆腐，双头龙对插磨穴", preset_name="anti_nsfw_ultra")[0])
        self.assertTrue(moderator.check_keywords("奴隶买卖私设刑房，赌场下注脚本刷币", preset_name="anti_nsfw_ultra")[0])
        self.assertTrue(moderator.check_keywords("今晚抢银行越狱，关进监狱调教奴隶", preset_name="anti_nsfw_ultra")[0])

        # xbbot 专属词库匹配
        self.assertTrue(moderator.check_keywords("强行买下奴隶并进行折磨奴隶", preset_name="xbbot_game")[0])

    def test_group_config_defaults(self):
        """测试群专属配置跟随全局默认"""
        from main import Msg2ImgPlugin
        plugin = Msg2ImgPlugin(context=None, config=dict(DEFAULT_CONFIG))
        # 默认空
        c = plugin._get_group_custom_config("123456")
        self.assertEqual(c, {})
        self.assertEqual(plugin._get_group_font_scale("123456"), 100)

    def test_presets_update_flow(self):
        """内置词库更新检测：过期本地标记更新，覆盖/保留后恢复一致"""
        import copy
        from core.config import ConfigManager
        mgr = ConfigManager()
        # 新鲜态：无更新
        self.assertFalse(mgr.get_presets_update_status()["update_available"])
        # 模拟旧版本残留（去掉 ultra 新增词）
        local = copy.deepcopy(mgr.config["keyword_presets"])
        ultra_kw = local["anti_nsfw_ultra"]["keywords"]
        trimmed = ultra_kw.replace(",抢银行,银行抢劫,银行劫案,银行,劫狱,越狱,监狱,奴隶", "")
        self.assertNotEqual(trimmed, ultra_kw)
        local["anti_nsfw_ultra"]["keywords"] = trimmed
        # 备份真实 config.json（apply/dismiss 会落盘）
        cfg_file = mgr.cfg_file
        bak = cfg_file.read_bytes() if cfg_file.exists() else None
        try:
            stale = ConfigManager({"keyword_presets": local, "builtin_presets_hash": "0" * 16})
            st2 = stale.get_presets_update_status()
            self.assertTrue(st2["update_available"])
            hit = [c for c in st2["changed"] if c["id"] == "anti_nsfw_ultra"]
            self.assertTrue(hit and hit[0]["added_total"] >= 8)
            st3 = stale.apply_builtin_presets(["anti_nsfw_ultra"])
            self.assertFalse(st3["update_available"])
            # dismiss 路径：保留本地同样消除提示（先清掉 apply 落盘的文件，还原过期现场）
            if stale.cfg_file.exists():
                stale.cfg_file.unlink()
            stale2 = ConfigManager({"keyword_presets": local, "builtin_presets_hash": "0" * 16})
            self.assertFalse(stale2.dismiss_builtin_presets_update()["update_available"])
        finally:
            if bak is not None:
                cfg_file.write_bytes(bak)
            elif cfg_file.exists():
                cfg_file.unlink()

    def test_font_fallback_after_delete(self):
        """删除正在使用的字体后回退：剩 1 个默认用它，多个切列表第一个，无可用清空回自动"""
        import shutil
        import tempfile
        import asyncio
        import main as main_mod
        from core import renderer as R
        from main import Msg2ImgPlugin
        tmp = Path(tempfile.mkdtemp())
        (tmp / "fonts").mkdir(parents=True, exist_ok=True)
        sim = Path("C:/Windows/Fonts/simhei.ttf").read_bytes()
        orig_subdir, orig_dd = R._data_subdir, R._FONT_DATA_DIR
        orig_req, orig_jr, orig_er = main_mod.request, main_mod.json_response, main_mod.error_response

        class Req:
            def __init__(self, p):
                self.p = p

            async def json(self, default=None):
                return self.p

        main_mod.json_response = lambda d: d
        main_mod.error_response = lambda msg, status_code=500: {"ok": False, "error": msg}

        async def call_delete(plugin, name):
            main_mod.request = Req({"name": name})
            return await plugin._api_fonts_delete()

        def fake_subdir(name=""):
            d = tmp / name if name else tmp
            d.mkdir(parents=True, exist_ok=True)
            return d

        # 备份 dev 配置（回退逻辑会落盘保存，避免污染其它用例）
        dev_cfg = Path("data/plugin_data/astrbot_plugin_xbimg/config.json")
        dev_bak = dev_cfg.read_bytes() if dev_cfg.exists() else None
        try:
            R._FONT_DATA_DIR = tmp
            R._data_subdir = fake_subdir
            plugin = Msg2ImgPlugin(context=None, config=None)
            plugin.cfg_mgr.data_dir = tmp
            fd = tmp / "fonts"

            def plant(*names):
                for n in list(fd.iterdir()):
                    n.unlink()
                for n in names:
                    (fd / n).write_bytes(sim)
                R.clear_font_cache()

            # A. 仅剩 1 个：默认使用它
            plant("aaa_one.ttf", "zzz_active.ttf")
            plugin.cfg_mgr.config.update({
                "font_source": "custom",
                "custom_font_path": str(fd / "zzz_active.ttf"),
                "custom_bold_font_path": "",
            })
            res = asyncio.run(call_delete(plugin, "zzz_active.ttf"))
            self.assertTrue(res["ok"])
            self.assertEqual(res["fallback"], "aaa_one.ttf")
            self.assertEqual(plugin.cfg_mgr.config["custom_font_path"], "aaa_one.ttf")
            # B. 多个：切换到列表第一个
            plant("aaa_one.ttf", "mmm_mid.ttf", "zzz_active.ttf")
            plugin.cfg_mgr.config.update({
                "font_source": "custom",
                "custom_font_path": str(fd / "mmm_mid.ttf"),
            })
            res = asyncio.run(call_delete(plugin, "mmm_mid.ttf"))
            self.assertTrue(res["ok"])
            self.assertEqual(res["fallback"], "aaa_one.ttf")
            # C. 无可用：清空回自动
            plant("solo.ttf")
            plugin.cfg_mgr.config.update({
                "font_source": "custom",
                "custom_font_path": str(fd / "solo.ttf"),
            })
            res = asyncio.run(call_delete(plugin, "solo.ttf"))
            self.assertTrue(res["ok"])
            self.assertEqual(res["fallback"], "")
            self.assertEqual(plugin.cfg_mgr.config["custom_font_path"], "")
        finally:
            R._data_subdir = orig_subdir
            R._FONT_DATA_DIR = orig_dd
            main_mod.request, main_mod.json_response, main_mod.error_response = orig_req, orig_jr, orig_er
            if dev_bak is not None:
                dev_cfg.write_bytes(dev_bak)
            elif dev_cfg.exists():
                dev_cfg.unlink()
            shutil.rmtree(tmp, ignore_errors=True)

    def test_decorative_font_fallback(self):
        """装饰字体（缺 CJK）自动回退：拉丁跟随主字体，中文切链中字体，国旗成对不断开"""
        from core.renderer import (
            _load_font_file, get_font, _font_covers, _resolve_char_font,
            _take_cluster, _cluster_codes,
        )
        latin = _load_font_file("C:/Windows/Fonts/arial.ttf", 32)  # 无 CJK，模拟哥特体
        cjk = get_font(32)
        self.assertIsNotNone(latin)
        self.assertTrue(_font_covers(latin, "A"))
        self.assertFalse(_font_covers(latin, "中"))
        self.assertTrue(_font_covers(cjk, "中"))
        self.assertTrue(_font_covers(latin, " "))
        self.assertIs(_resolve_char_font("A", latin), latin)
        fb = _resolve_char_font("中", latin)
        self.assertIsNot(fb, latin)
        self.assertTrue(_font_covers(fb, "中"))
        cl, ni = _take_cluster("🇨🇳好", 0)
        self.assertEqual(cl, "🇨🇳")
        self.assertEqual(ni, 2)
        self.assertEqual(_cluster_codes(cl), ["1f1e8-1f1f3"])

    def test_ios_emoji_download_offline(self):
        """无网络时 iOS 下载如实失败，不写 ready 标记，不虚标已下载"""
        import shutil
        import tempfile
        from core import renderer as R
        tmp = Path(tempfile.mkdtemp())
        orig_subdir, orig_dd = R._data_subdir, R._FONT_DATA_DIR
        orig_fetch = R._fetch_remote_emoji

        def fake_subdir(name=""):
            d = tmp / name if name else tmp
            d.mkdir(parents=True, exist_ok=True)
            return d

        try:
            R._FONT_DATA_DIR = tmp
            R._data_subdir = fake_subdir
            R._fetch_remote_emoji = lambda code, dest: False
            res = R.download_emoji_pack("ios")
            self.assertFalse(res["ok"])
            self.assertFalse((tmp / "emoji" / "ios_pack.ready").exists())
            packs = {p["id"]: p for p in R.get_emoji_packs_status()}
            self.assertFalse(packs["ios"]["installed"])
        finally:
            R._data_subdir = orig_subdir
            R._FONT_DATA_DIR = orig_dd
            R._fetch_remote_emoji = orig_fetch
            shutil.rmtree(tmp, ignore_errors=True)

    def test_curated_download_retries(self):
        """精选字体单文件波动失败时重试并最终成功；持续失败则如实报错"""
        import shutil
        import tempfile
        import time as _t
        from core import renderer as R
        tmp = Path(tempfile.mkdtemp())
        (tmp / "fonts").mkdir(parents=True, exist_ok=True)
        sim = Path("C:/Windows/Fonts/simhei.ttf").read_bytes()
        orig_subdir, orig_dd = R._data_subdir, R._FONT_DATA_DIR
        orig_dl = R._download_file
        orig_sleep = _t.sleep
        calls = {"n": 0}

        def fake_subdir(name=""):
            d = tmp / name if name else tmp
            d.mkdir(parents=True, exist_ok=True)
            return d

        def flaky(url, dest):
            calls["n"] += 1
            if calls["n"] < 3:
                return False, "波动"
            dest.write_bytes(sim)
            return True, ""

        try:
            R._FONT_DATA_DIR = tmp
            R._data_subdir = fake_subdir
            R._download_file = flaky
            _t.sleep = lambda s: None
            R.clear_font_cache()
            res = R.download_curated_font("lxgw_wenkai")  # 单文件包
            self.assertTrue(res["ok"])
            self.assertEqual(calls["n"], 3)
            self.assertTrue(res["downloaded"])
            # 持续失败：如实报错
            R._download_file = lambda url, dest: (False, "断网")
            (tmp / "fonts" / "LXGWWenKai-Regular.ttf").unlink(missing_ok=True)
            R.clear_font_cache()
            res2 = R.download_curated_font("lxgw_wenkai")
            self.assertFalse(res2["ok"])
            self.assertIn("LXGWWenKai-Regular.ttf", res2["error"])
        finally:
            R._data_subdir = orig_subdir
            R._FONT_DATA_DIR = orig_dd
            R._download_file = orig_dl
            _t.sleep = orig_sleep
            shutil.rmtree(tmp, ignore_errors=True)

    def test_emoji_downloading_tmp_ignored(self):
        """下载残留 tmp 不计入占用；失败不留残留文件"""
        import shutil
        import tempfile
        import urllib.request
        from core import renderer as R
        tmp = Path(tempfile.mkdtemp())
        orig_subdir, orig_dd = R._data_subdir, R._FONT_DATA_DIR
        orig_dead = R._EMOJI_REMOTE_DEAD_UNTIL
        orig_urlopen = urllib.request.urlopen

        def fake_subdir(name=""):
            d = tmp / name if name else tmp
            d.mkdir(parents=True, exist_ok=True)
            return d

        try:
            R._FONT_DATA_DIR = tmp
            R._data_subdir = fake_subdir
            ed = tmp / "emoji"
            ed.mkdir(parents=True, exist_ok=True)
            (ed / "2705.png").write_bytes(b"0" * 4096)
            (ed / "2705.png.downloading").write_bytes(b"0" * 700)  # 模拟中断残留
            self.assertEqual(R.get_emoji_storage_kb("ios"), round(4096 / 1024, 1))
            # urlopen 直接抛错：不应留下新的 tmp
            def boom(req, timeout=None):
                raise urllib.request.URLError("down")
            urllib.request.urlopen = boom
            R._EMOJI_REMOTE_DEAD_UNTIL = 0.0
            self.assertFalse(R._fetch_remote_emoji("1f600", ed))
            leftovers = list(ed.glob("1f600.png.downloading"))
            self.assertEqual(leftovers, [])
            R._EMOJI_REMOTE_DEAD_UNTIL = 0.0  # 退避后仍可工作由其它用例覆盖，此处仅复位
        finally:
            R._data_subdir = orig_subdir
            R._FONT_DATA_DIR = orig_dd
            R._EMOJI_REMOTE_DEAD_UNTIL = orig_dead
            urllib.request.urlopen = orig_urlopen
            shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    unittest.main()
